-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3307:3307
-- Generation Time: Jun 25, 2023 at 07:12 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pwa`
--

-- --------------------------------------------------------

--
-- Table structure for table `korisnik`
--

CREATE TABLE `korisnik` (
  `idx` int(11) NOT NULL,
  `ime` varchar(45) NOT NULL,
  `prezime` varchar(45) NOT NULL,
  `username` varchar(45) NOT NULL,
  `sifra` varchar(255) NOT NULL,
  `razina` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `korisnik`
--

INSERT INTO `korisnik` (`idx`, `ime`, `prezime`, `username`, `sifra`, `razina`) VALUES
(14, 'Branimir', 'Hrsto', 'bhrsto', '$2y$10$C23fUmzhkkpGuchN35CMVuRx6OtoA7yCTLld6gS1iBOSTgQa6cM2e', 1),
(15, 'test', 'test', 'test', '$2y$10$wlfVzBswGGFkVm1Oup4l..xyTevYUfrHS7gCu5PptpnW.EQ2Tvw1O', 0);

-- --------------------------------------------------------

--
-- Table structure for table `unos`
--

CREATE TABLE `unos` (
  `id` int(11) NOT NULL,
  `naslov` varchar(64) NOT NULL,
  `kratakSadrzaj` text NOT NULL,
  `sadrzaj` text NOT NULL,
  `slika` varchar(64) NOT NULL,
  `kategorija` varchar(64) NOT NULL,
  `arhiva` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `unos`
--

INSERT INTO `unos` (`id`, `naslov`, `kratakSadrzaj`, `sadrzaj`, `slika`, `kategorija`, `arhiva`) VALUES
(3, 'Njemačka reprezentacija u hokeju oduševila', 'Svatko tko je pogledao u lica njemačkih igrača nekoliko sekundi nakon posljednje sirene vidio je čisto razočaranje, veliku frustraciju i suzu ili dvije. Nema sumnje: finalni poraz na Svjetskom prvenstvu u hokeju na ledu protiv rekordnih svjetskih prvaka Kanade je zabolio.', ' No, bio je to poraz iz kojeg je kao pobjednik izašla momčad Njemačkog hokejaškog saveza (DEB). Ne treba vam ni srebro, prvo odličje na Svjetskom prvenstvu od 1953., da bi se dokazalo da je ova reprezentacija postigla velike stvari. Iznad svega, način na koji je došlo do ovog uspjeha.\r\n\r\n                    Osvrnimo se nekoliko tjedana unatrag. Nacionalni trener Harold Kreis prikupio je više odbijenica od potencijalnih najboljih igrača gotovo svaki dan nego prosječan zaposlenik u procesu prijave za novi posao.<br><br> Između ostalog, nasljednik Tonija Söderholma zbog ozljeda je morao bez dvojice napadača Andreasa Edera i Yasina Ehliza te NHL profesionalaca Tima Stützlea, Leona Draisaitla i Philippa Grubauera. Popis se može nastaviti unedogled. Kao rezultat toga, Kreis i njegova šarolika ekipa nisu imali puno vremena da se priviknu na to. Nakon teških priprema uslijedio je otrežnjujući početak Svjetskog prvenstva s tri poraza zaredom - ali i protiv najboljih nacija Švedske, Finske i SAD-a.\r\n                    \r\n                    Ali što je krug napravio? Ostao je smiren i staložen, baš kao iu posljednjim klupskim boravcima u Schwenningenu i Düsseldorfu.<br><br>Umjesto toga vjerovao je igračima koji su mu bili na raspolaganju – a oni su mu dvostruko i trostruko uzvratili učinkom. S leđima okrenutim zidu, njemački tim je razvio zamah i koheziju koji će ih odvesti do finala. Sa svakom pobjedom raslo je i samopouzdanje i pokazalo se da za velike stvari nisu potrebna nužno velika imena.\r\n                    \r\n                    Sturm, Kai Wissmann i Leon Gawanke donijeli su nešto dodatno svojom individualnom kvalitetom, no prije svega igrači iz zadnjih redova, poput turnirskog otkrića Wojciecha Stachowiaka, Frederika Tiffelsa, Alexandera Ehla i Daniela Fischbucha, također su osvajali bodove i izazvao komešanje zabrinuti. Kreis je svojim načinom vođenja ljudi uspio postići da se svaki član DEB-a, od vratara do menadžera, osjeća važnim i cijenjenim. Čimbenik koji se ne smije podcijeniti tijekom turnira.', 'hokej.jpg', 'sport', 0),
(6, 'BVB drama i prvo kolo za tenisača Niemeiera', 'Tenisačica Jule Niemeier se morala nositi s vlastitim neuspjehom u prvom kolu French Opena na blagdan Duhova.', ' Rođena u Dortmundu, poput navijača BVB-a Jan-Lennarda Struffa s Grand Slam turnira u Parizu, uzalud je grozničala u borbi za naslov Bundeslige s Borussijom.\r\n\r\n                    “Iznimno je boljelo. I danas sam to primijetila\", ispričala je 23-godišnjakinja o svojim osjećajima u nedjelju kasno navečer. “Dolazeći iz grada znate što bi to značilo za klub i cijeli grad. Osjećao sam se kao poraz, kao da sam igrao samog sebe.Sada sam izgubio dva dana zaredom, osjetio sam, tako da sam imao dva vrlo skromna dana.\"<br><br> \r\n                    \r\n                    BVB je propustio priliku osvojiti njemačko prvenstvo nakon što je u dugom duelu s FC Bayern Münchenom pobijedio FSV Mainz 05 2-2.<br><br> \r\n                    \r\n                    Sam Niemeier ispao je odmah na startu od Ruskinje Darje Kasatkine s 3:6, 4:6. S tribina ju je bodrila i njezina bivša partnerica u igri parova Andrea Petković, koja je sjedila pokraj trenera Christophera Kasa. “Ona ima puno iskustva, svakako je dobro imati nekoga takvog u timu i razmjenjivati ​​ideje i učiti stvari”, rekao je Niemeier o suradnji. “Naravno da se nadam da će tako ostati i ubuduće i da će s vremena na vrijeme moći prisustvovati utakmicama ili turnirima.', 'tenis.jpg', 'sport', 1),
(7, 'Izborne vlasti potvrdile Erdoganovu pobjedu', 'Izborna noć u Turskoj polako donosi izvjesnost. Recep Tayyip Erdogan ponovno je izabran za šefa države. U glavnom gradu Ankari već čeka razdragana publika.', 'Aktualni predsjednik Recep Tayyip Erdogan pobijedio je u drugom krugu predsjedničkih izbora u Turskoj. Erdogan je izabran za 13. predsjednika Turske, rekao je šef izbornog tijela Ahmet Yener u nedjelju u Ankari.\r\n                    Turski predsjednik Recep Tayyip Erdogan već se prije kraja prebrojavanja glasova proglasio pobjednikom predsjedničkih izbora. Zahvaljuje svima koji su mu omogućili da vlada sljedećih pet godina, rekao je Erdogan razdraganim pristalicama u nedjelju u Istanbulu. Bit će sa svojim sljedbenicima “do groba”. U Ankari su kolone automobila sa zastavama koje se vijore već predvečer ispunjavale ulice. Koncerti za rog mogli su se čuti i u Istanbulu. <br><br>\r\n                    \r\n                    Kao i u predizbornoj kampanji, Erdogan je agitirao protiv lezbijki, homoseksualaca, biseksualaca i transrodnih osoba. \"Braćo moja, nije li ovo CHP za LGBT?\", rekao je u nedjelju, misleći na Kilicdarogluovu stranku. U vlastitom izbornom savezu, smatra Erdogan, toga nema. Dobio je snažan pljesak publike.\r\n                    \r\n                    Viktor Orban među prvima je čestitao turskom šefu države Recepu Tayyipu Erdoganu pobjedu, također prije objave službenih rezultata izbora. Mađarski premijer napisao je u nedjelju na Twitteru o \"neupitnoj izbornoj pobjedi\". Katarski emir Tamim bin Hamad Al Thani i libijski premijer Abdul Hamid Dbaiba prethodno su čestitali šefu turske države. \"Dragi moj brate Recep Tayyip Erdogane, čestitam ti na pobjedi\", napisao je šef katarske države na Twitteru u nedjelju.<br><br>\r\n                    \r\n                    Oporba zasad nije komentirala rezultate. Kilicdaroglu je želio komentirati kasnije tijekom večeri. Prema izbornim vlastima, dan glasovanja protekao je tiho, ali je bilo nekoliko izvješća o nasilnim incidentima.\r\n                    \r\n                    Kampanja je bila nepoštena. Osim što je kontrolirao medije, Erdogan je mogao crpiti i državne resurse. U prvom glasanju, na kojem je Erdogan pobijedio, bilo je izvještaja o nepravilnostima, ali to nije promijenilo ishod izbora.', 'turska.jpg', 'politika', 1),
(11, 'U starosti se bez vozačkih ispita ne može', 'Stariji su ljudi među glavnim uzrocima nesreća koje uključuju tjelesne ozljede. To ne smije dovesti do diskriminirajućih propisa. Ali ne možete samo ostaviti sve kako jest', '90-godišnjak se autom zabio u kolonu automobila nakon što je promijenio trak i izazvao višesatni prometni kaos na Rheinkniebrücke u Düsseldorfu. On i njegova suputnica su teže ozlijeđeni, ostali barem lakše. Tragični slučaj opet otvara pitanje koliko pogotovo stariji vozači mogu ugroziti javni prijevoz.\r\n\r\n                    Statistika govori jasnim jezikom. U slučaju nesreća koje uključuju tjelesne ozljede, vozač je glavni krivac u 75 posto osoba starijih od 75 godina. I uglavnom su to muškarci. Sličnu visoku stopu inače postižu samo mladi od 18 do 21 godine, od kojih 70 posto uzrokuje vozač. Kod vozača u dobi od 45 do 55 godina samo je polovica glavnih krivaca. Ako pribrojite kilometražu, na milijardu prijeđenih kilometara umire devet ljudi jer su vozači stariji od 75 godina bili neoprezni. <br><br>\r\n                    \r\n                    Taj je broj jednako visok za mlade (od 18 do 21 godine), dok su osobe od 45 do 64 godine uzročnici nesreća s gotovo dva smrtna slučaja na milijardu prijeđenih kilometara. Sličan je i omjer osobnih ozljeda. Opće udruženje njemačke industrije osiguranja (GDV) utvrdilo je te brojke. \"Za vozače starije od 75 godina, rizik od izazivanja nesreća se znatno povećava\", sažima Siegfried Brockmann, koji vodi odjel za istraživanje nesreća u GDV-u.\r\n                    \r\n                    To ne znači da su svi stariji ljudi loši vozači. Neki od njih nevjerojatno dobro vladaju svojim automobilima do duboke starosti, pametni su, oprezni i iskusni vozači. A jasno je i da su, pogotovo u ruralnim područjima, stariji ljudi potpuno nepokretni bez automobila. Iz tih razloga većina prometnih političara izbjegava poduzimanje grupnih radnji protiv velikog broja nesreća koje uzrokuju stariji ljudi. Jer ne smije se dogoditi da ljudi budu diskriminirani isključivo zbog godina. <br><br>\r\n                    \r\n                    S druge strane, opasnost koju predstavljaju neki stariji vozači nije faktor koji se može zanemariti. Iako su istraživanja nesreća znatno napredovala i broj osobnih ozljeda drastično pao, neravnoteža u dobnim skupinama je vrlo jasna. Zakonodavac je već reagirao na mlade generacije. Tamo je granica alkohola nula i postoji probna vozačka dozvola. \"Ovo uzima u obzir neiskustvo, a ponekad i naglost mlađih vozača\", kaže istraživač nesreća Brockmann.', 'vozac.jpg', 'politika', 0),
(28, 'Potpuno shvaćam Livaju', '\"Trebalo je odmah prekinuti trening i povući momčad s terena\", kaže Mišo Krstičević', 'Dan nakon što je Marko Livaja napustio tabor hrvatske reprezentacije, komentar cijele situacije potražili smo kod četvorice splitskih trenera.\r\n\r\nMišo Krstičević, trener Jadrana LP:\r\n\r\n- Kao igrač Hajduka bio sam u prilici doživjeti kojekakve ružne ispade na gostujućim terenima, ali ovi događaji na Rujevici prevršili su svaku mjeru. Teško je bilo predvidjeti, čak nemoguće, da će se jedna ugodna seansa, kao što je otvoreni trening naše reprezentacije, pretvoriti u pravi skandal. Nema tolerancije za takve besprizorne ispade. Moj je dojam da je došlo do zakasnjele reakcije ljudi zaduženih za sigurnost, ali i igrača, pogotovo izbornika Dalića. Trebalo je, prema mojem uvjerenju, odmah prekinuti trening, povući momčad s terena, tako se solidarizirati s Livajom.\r\n\r\nLuka Bonačić, bivši trener Hajduka, ali i brojnih klubova kod nas i u inozemstvu:\r\n\r\n- Ponašanje Livaje nakon toliko gnjusnih uvreda moglo se očekivati, ljudski je da čovjek brani svoj integritet. Šteta je da se odgovorni za osiguranje nisu snašli. Prava lekcija neodgovornima bila bi da je Dalić naredio da se, barem nakratko, prekine trening i isprazni tribina.', 'livaja.jpg', 'sport', 0),
(29, 'Istina o transferu Petkovića', 'Pojavile su se glasine i o Josipu Šutalu te Dominiku Livakoviću...', 'Turski su medijski \"bombarderi\" opet u akciji. Pa je tako u srijedu osvanula \"senzacionalna\" vijest da je Dinamov napadač Bruno Petković prodan Trabzonsporu, navedena je čak i odšteta, kao i Petkovićeva plaća. Nedostajale su tek fotografije velebne vile u kojoj će Petković živjeti u Trabzonsporu...\r\n\r\nMeđutim, te su informacije, kao i u većini slučajeva, bile lažne i olako su, bez temeljne provjere, bile prenesene i u hrvatskim medijima. Istina je, naime, da Trabzonspor uopće nije kontaktirao Dinamo u svezi spomenutog transfera! Niti je bilo nekakvog dogovora o prvim kontaktima, niti je poslana preliminarna ponuda, a nije se tražio ni sastanak vodstva klubova. Potvrdu ovih činjenica dobili smo izravno u turskom klubu - dakle, ne da Petković nije prodan u Trabzonspor, nego čak i špekulacije oko tog možebitnog transfera graniče s istinom.\r\n\r\nTrabzonspor će ove sezone, na čelu s trenerom Nenadom Bjelicom, rekonstruirati momčad i sigurno naš strateg ima \"na radaru\" i neke hrvatske igrače. Uz 20-ak ostalih... No, Petkovićev odlazak u ovaj klub zasad je daleko od realizacije, maksimirski klub sigurno neće drastično spustiti odštetu i pustiti Petkovića za \"sitniš\".\r\n\r\nA prema određenim informacijama, ni Dinamovu reprezentativnom napadaču baš se ne ide u ovaj grad na obali Crnog mora, u blizini turske granice s Gruzijom i Armenijom, udaljen više od tisuću kilometara od Istanbula. Doznali smo, k tome, da za Petkovića postoji i zanimanje iz SAD-a (MLS) i Saudijske Arabije, no konkretne ponude još nisu stigle u plavi salon...\r\n\r\nVEZANE VIJESTI\r\n29142975Video icon\r\nNAJBOLJE OD NAJBOLJEG\r\nANKETA/VIDEO Glasajte za najljepši gol sezone u HNL-u: Škarice, vanjska ili slobodnjak?\r\nZARADA ŽIVOTA\r\nPonuda bez presedana: Nevjerojatno koga nakon Ronalda i Benzeme kupuju bogati Saudijci!\r\nU vremenu špekulacija uoči prijelaznog roka, procurile su i glasine da je francuski Lyon zainteresiran za Josipa Šutala, a zanimanje za vratara Dominika Livakovića navodno stiže i iz Saudijske Arabije. Nikakve potvrde tih šaputanja nema i sve je u zasad u sferi \"želja i pozdrava\". Bit će još ovakvih \"nabadanja\", znano je da se uoči vjenčanja i prijelaznog roka svašta nudi, obećava se i obznanjuje nemoguće.\r\n\r\nUglavnom, Dinamo je i dalje u \"tihim\" pregovorima s Lokomotivom i Rijekom oko Kačavende, Stojkovića i Frigana. No, sigurno je da neće \"ludovati\" i ne budu li odštetni zahtjevi spomenutih klubova u granicama normale, od tih transfera neće biti ništa.\r\n\r\nA doznali smo i da dolazak francuskog srednjeg braniča Maximea Bernauera vrlo vjerojatno neće biti jedini dolazak nekog inozemnog igrača u Maksimir. Zasad su imena nogometaša zanimljivih Plavima pod velom tajne, no Dinamo se želi, kako kažu u klubu, \"otvoriti prema Europi\"...', 'petković.jpg', 'sport', 1),
(30, 'Brozović prodan Saudijcima! ', 'Brozoviću  se navodno svidjela financijski bolja ponuda Saudijaca.', 'Prema napisima u talijanskim medijima ovakav ishod podupirali su agenti Marcela Brozovića kojima se navodno svidjela financijski bolja ponuda Saudijaca. Inter je tražio 20 milijuna eura koje Barcelona nije ponudila. Katalonci su se nadali spustiti cijenu, no prema informacijama Gianluce Di Marzia vatreni je već prodan. Fabrizio Romano javlja kako dogovora još nema, a ključne odluke donosit će se tek u ponedjeljak.\r\n\r\nGianluca Di Marzio piše kako je Inter ipak prodao Marcela Brozovića u saudijski Al Nassr za 23 milijuna eura. Poznati transfer insajder objavio je i detalje koje je hrvatski reprezentativni veznjak dogovorio s saudijskim klubom u kojemu će mu suigrač biti slavni Cristiano Ronaldo.\r\n\r\nPonajprije, njegova godišnja zarada iznosit će 20 milijuna eura godišnje, a ugovor će trajati tri godine. To je osam milijuna više, no što je do sada dobivao u Interu. Prema navodima Di Marzija, Barcelona mu je nudila sedam milijuna godišnje.\r\n\r\nOvakav ishod, pišu talijanski mediji, podupirali su i Brozovićevi agenti kojima se navodno više svidjela financijski bolja ponuda Saudijaca, od europskih travnjaka i prestiža igranja u Barceloni koja je nudila poprilično manji iznos. U svakom slučaju još treba pričekati komentar iz Brozovićevog tima.\r\n\r\nDrugu stranu priče predstavlja Fabrizio Romano. U nedjelju popodne ovaj transfer insajder je objavio kako će se ključne odluke donositi tek u ponedjeljak, a premda su Saudijci uvjereni da će pridobiti hrvatskog reprezentativca, na kraju će sve ovisiti o odluci njega i njegovog tima.', 'broz.jpeg', 'sport', 0),
(31, 'Gvardiol blizu Etihada!', 'Manchester City je poslao ponudu koja bi uz bonuse mogla prelaziti cijenu koju Leipzig traži', 'Dinamo je Joška Gvardiola pred dvije godine prodao RB Leipzigu za 18.8 milijuna eura. Od tada se 21-godišnjak isprofilirao u najskupljeg braniča svih vremena za kojega klub može tražiti 100 milijuna. Manchester City je poslao ponudu, javljaju njemački mediji, koja bi uz bonuse mogla prelaziti cijenu koju Leipzig traži.\r\nNijemci se pak nadaju zadržati 21-godišnjeg braniča još barem godinu dana i neće prihvatiti ponudu ispod 100 milijuna eura. Ponuda o kojoj izvještava njemački medij bi uz bonuse zasigurno prelazila 100 milijuna eura pa se nadaju da će Leipzig ipak odlučiti provesti najskuplji transfer braniča u povijesti. Romano pak navodi kako će City rad na rekordnom transferu nastavi idućeg tjedna uz novu ponudu.\r\n\r\nTrenutno rekord drži Harry Maguire kojega je Manchester United još 2019. kupio za velikih 87 milijuna eura. Što višoj cijeni nada se i Dinamo. Prema ugovoru koje je s Leipzigom sklopljen prilikom Gvardiolovog prvog transfera, hrvatski prvak od zarade prilikom iduće prodaje dobiva 20 posto.\r\n\r\nObzirom da je Dinamo Gvardiola prije dvije godine prodao uz odštetu od 18.8 milijuna eura, u slučaju prodaje za 100 milijuna, Nijemci će na braniču zaraditi 81.2 milijuna eura. Upravo u tom iznosu Dinamo ima 20 posto, što znači oko 16 milijuna eura. Stoga se na Maksimiru nadaju što boljim pregovaračkim sposobnostima Nijemaca.', 'gvardiol.jpeg', 'sport', 1),
(32, 'Preokret u Rusiji', 'Američke obavještajne službe imale su podatke da šef Wagnerovaca nešto sprema.', 'Američke obavještajne službe danima ranije imale su naznake da Jevgenij Prigožin nešto planira. Prikupili su u posljednja dva tjedna podatke da vođa Wagnerovih plaćenika planira oružanu akciju protiv državnog vojnog vrha i obavijestile Bijelu kuću. \r\n\r\nVladimir Putin je zasigurno isto znao, sigurno nije saznao 24 sata prije, pišu Washington Post i New York Times. \r\nOsim Bijele kuće, visoki dužnosnici Pentagona, State Departmenta i Kongresa bili su obaviješteni u posljednja dva tjedna o obavještajnim podacima. Točna priroda i vrijeme Prigožinovih planova nisu bili jasni sve do njegovog zapanjujućeg preuzimanja vojnog zapovjedništva i tenkovske vožnje prema Moskvi u petak i subotu. Ali bilo je dovoljno signala da se vodstvu može reći da se nešto sprema. Tako da mislim da su bili spremni za to. Tijekom posljednja dva tjedna postojala je velika zabrinutost oko toga što bi se moglo dogoditi - hoće li ruski predsjednik Vladimir Putin ostati na vlasti i što bi nestabilnost mogla značiti za kontrolu ruskog nuklearnog arsenala - piše Washington Post ne otkrivajući, dakako, identitet američkih dužnosnika kao svojih izvora ovih informacija.\r\n\r\nAmeričke obavještajne agencije, podsjetimo, znale su i da se Putin planira invaziju na Ukrajinu. Krajem 2021. je SAD upozoravao svijet na to, ovog puta nisu digli uzbunu u javnosti. Naime, američki dužnosnici smatrali su da bi ih Putin mogao optužiti da su orkestrirali puč ako izađu s ovim podacima u javnost, a očito im i nije bilo u interesu pomoći mu. Inače, Prigožina u Americi terete da je utjecao na predsjedničke izbore 2016. u korist Donalda Trumpa.\r\nPrigožin se suočio s malim otporom kada su on i njegove snage umarširali u Rostov na Donu i preuzeli kontrolu nad tamošnjim stožerom Južnog vojnog okruga, primijetili su zapadni i američki obavještajni dužnosnici, ocijenivši to pokazateljem da uživa određenu razinu potpore i među regularnim vojnim snagama, kao i ruske sigurnosne službe. Obavještajni analitičari promatraju što slijedi.', 'putin.webp', 'politika', 0),
(33, 'Što slijedi nakon puča?', 'Prigožin je povukao vojsku iz Rusije pa nestao iz javnosti\r\n', 'Specijalna vojna operacija u Ukrajini moj je prioritet. Dan počinjem time i time ga završavam, u stalnom sam stalnom kontaktu s Ministarstvom obrane, govori ruski predsjednika Vladimir Putin na državnoj televiziji, koja je pustila njegov govor koji je snimljen prije pokušaja državnog udara.\r\nNakon što su borci plaćeničke skupine Wagner pod vodstvom Jevgenija Prigožina u subotu zauzeli dva ruska grada, Rostov na Donu i Voronjež te krenuli prema Moskvi Putin je bio oštriji i najavljivao da će sve kazniti, ali je u međuvremenu svima ponudio amnestiju.\r\n\r\n- Ovo je zločinačka kampanja. Jednaka je oružanoj pobuni. Rusija će se braniti. Borimo se za život i sigurnost naših građana i naš teritorijalni integritet. To je pokušaj podmetanja iznutra. To je izdaja. Borimo se protiv anarhije i kapitulacije. Ova unutarnja pobuna je za nas smrtni udarac. Činim sve da odbijem ovaj napad. Osobni interesi su doveli do izdaje naše zemlje i uzroka zbog kojeg se bore naše oružane snage. Svi koji su krenuli putem izdaje bit će kažnjeni i za to će odgovarati - govorio je Putin da bi nekoliko sati nakon toga nestao, a njegov avion misteriozno poletio iz Moskve.\r\n\r\nU sve se uključio Putinov najodaniji saveznik Aleksandar Lukašenko, bjeloruski predsjednik, koji je u Putinovo ime pregovarao s Prigožinom.\r\n- Što se tiče Prigožina, njegova sudbina je vrlo neizvjesna. Ako Putin želi ostati na vlasti, barem po onoj retorici koju smo imali prilike slušati u subotu, onda Prigožinu nema mjesta na ovome svijetu. Jednostavno, to apsolutno ne dolazi u obzir. Rusi i dalje trebaju skupinu kao što je Wagner. Prigožin je još uvijek na čelu Wagnera. Koliko dugo će ostati, na koji način će se to razriješiti, to ćemo tek vidjeti u budućnosti i u vrlo doglednoj budućnosti. Hoće li on uopće ostati ili opet kažem, ako je ovo scenarij, ako je ovo nekakva dogovorena predstava, onda definitivno Prigožin ima i dalje svoje mjesto i ulogu u svemu tome - pojasnio je Ogorec. Još uvijek je nejasno, kaže Ogorec, kako će ova pobuna utjecati na Putinovu poziciju.', 'puc.webp', 'politika', 0),
(34, 'Plenković otvorio Picokijadu', 'Čestitam na očuvanju sjajne tradicije, ovo je važan događaj', 'Predsjednik Vlade Andrej Plenković otvorio je u subotu 55. Picokijadu, tradicionalnu kulturno-turističku manifestaciju koja se održava kao spomen na legendarnu obranu Đurđevčana od napada Turaka.\r\n\r\n- Ovo je svakako važan događaj i čestitam na očuvanju sjajne tradicije i na evociranju hrabrosti Đurđevčana od prije nešto manje od petsto godina kada su u borbi protiv Osmanlija pokazali otpornosti, ali i kreativnost- rekao je Plenković.\r\n\r\nDodao je kako program koji traje već desetak dana i ogroman broj posjetitelja pokazuju kako kontinentalna Hrvatska, u tom slučaju Đurđevac i Koprivničko-križevačka županija nalaze načine da privuku turiste.\r\n\r\nPo njegovim riječima, cijela Hrvatska pulsira brojnim događanjima tijekom ljetnih mjeseci, a podaci pokazuju da raste broj posjeta i noćenja.\r\n\r\nPlenković je podsjetio da je zadnji put bio u Đurđevcu kada se otvarao Poduzetnički centar, gdje danas podržavaju brojne projekte EU i nacionalnim sredstvima. Neki od njih su Mali princ, Centar za osobe s invaliditetom, Dom za starije, a obnova Starog grada financirat će se sredstvima iz Nacionalnog plana oporavka i otpornosti.\r\n\r\nĐurđevački gradonačelnik Hrvoje Janči rekao je da će ove godine po 55. ući u legendu i ponovno obraniti grad, a drago mu je što je lijepo vrijeme pa je na tu veliku kulturnu manifestaciju došlo puno ljudi.\r\n\r\nSredišnji dio Picokijade, koja se održava od 1968., je \"Legenda o picokima\", spektakl u režiji Krešimira Dolenčića, s oko četiri stotine sudionika, od članova povijesne postrojbe preko konjanika do lokalnog stanovništva.\r\n\r\nTo masovno scensko djelo slavi baštinu i junačku prošlost tog kraja, uz pirotehničke i audiovizualne efekte, scene borbe, mitološka bića, tradicijske napjeve i govori o povijesnoj pobjedi mještana nad moćnijim Turcima.', 'plenki.webp', 'politika', 1),
(35, 'Besplatni vrtići su bitni!', 'SDP poručuje kako vrtići trebaju biti dostupni svakom djetetu', 'Predsjednik Socijaldemokratske partije (SDP) Hrvatske Peđa Grbin poručio je u subotu da SDP želi svoj djeci u Hrvatskoj omogućiti besplatne vrtiće, uz upozorenje da Hrvatska ima jednu od najnižih stopa pohađanja vrtića u EU i snažan pad nataliteta.\r\n\r\nSDP poručuje kako vrtići trebaju biti dostupni svakom djetetu, bez obzira na njegovu socijalnu i ekonomsku situaciju ili mjesto u kojem živi, jer oni omogućuju sigurnost i smanjivanje socijalne nejednakosti te djeci pružaju više od obrazovanja.\r\n\r\nUvođenje besplatnih vrtića korisno je za roditelje jer im olakšava ekonomske troškove podizanja djece, pomaže ravnopravnosti spolova jer povećanjem broja vrtića i otklanjanjem financijskog tereta ženama se olakšava rad i izgradnja karijere, a ulaganje u djecu jedina je prava demografska mjera.\r\n\r\nGrbin je upozorio kako je upravo zbog niskih stopa pohađanja vrtića i pada nataliteta nužno ulaganje u besplatne vrtiće i povećanje njihovih kapaciteta.\r\n\r\nU SDP-u su svjesni problema nedostatka mjesta u vrtićima, kao i manjka odgojitelja, a izgradnja novih i proširenje postojećih kapaciteta dugotrajan je proces na kojem treba početi raditi odmah.\r\n\r\nGrbin je naveo da će to ostvariti prvenstveno povećanjem izdvajanja, tako da se država uključi u financiranje vrtića, ali upravljanje ostaje na lokalnoj zajednici, koja najbolje prepoznaje potrebe svoje sredine.\r\n\r\nPo prijedlogu SDP-a, država bi godišnje utvrđivala prosječnu cijenu vrtića, što bi to iznosilo otprilike 350 eura po djetetu i od toga preuzela pola iznosa.\r\n\r\nTime bi, tvrde, prestala potreba za daljnjom participacijom roditelja u javnim vrtićima, a u sustavu bi se osigurala dodatna sredstva za povećanje plaća odgojitelja, podizanje standarda i gradnju novih vrtića.\r\n\r\n\"To je mjera koja bi državu, odnosno proračun, koštala 300 milijuna eura godišnje. S time možemo ostvariti da svako dijete ide u vrtić, a njegovi roditelji ne moraju plaćati nikakve participacije\", rekao je Grbin.\r\n\r\nNa primjeru Pule može se vidjeti kako bi to izgledalo. Umjesto 90 eura, koliko danas roditelji plaćaju za djecu koja idu u vrtiće, roditelji ne bi morali plaćati ništa.\r\n\r\nNapomenuo je kako bi bila osigurana daljnja sredstva koja bi omogućila da se unutar četiri godine može otvoriti, ovisno o uspješnosti lokalne samouprave, od 100 do 200 novih mjesta.\r\n\r\n\"To je dobra mjera, korisna za roditelje, ali isto tako i demografska mjera. Podsjećam da je u 10 godina broj rođene djece pao s nešto iznad 40.000, koliko je bilo u 2013. godini, na 34.000, koliko je rođeno lani\", kaže Grbin.', 'pedja.webp', 'politika', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `korisnik`
--
ALTER TABLE `korisnik`
  ADD PRIMARY KEY (`idx`),
  ADD UNIQUE KEY `username` (`username`);

--
-- Indexes for table `unos`
--
ALTER TABLE `unos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `korisnik`
--
ALTER TABLE `korisnik`
  MODIFY `idx` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT for table `unos`
--
ALTER TABLE `unos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
